import type { ZodType } from "zod";

import {
  BROWSER_AUTHENTICATE_HTTP_ACTION,
  BROWSER_CHECK_ACTION,
  BROWSER_CLICK_ACTION,
  BROWSER_CLICK_AT_ACTION,
  BROWSER_CLOSE_TAB_ACTION,
  BROWSER_EVALUATE_ACTION,
  BROWSER_EXECUTE_JAVASCRIPT_ACTION,
  BROWSER_FIND_ELEMENTS_ACTION,
  BROWSER_FIND_NATURAL_LANGUAGE_ACTION,
  BROWSER_GET_HTTP_AUTH_STATE_ACTION,
  BROWSER_GET_PAGE_SNAPSHOT_ACTION,
  BROWSER_GET_PAGE_TEXT_ACTION,
  BROWSER_HANDLE_JAVASCRIPT_DIALOG_ACTION,
  BROWSER_LIST_TABS_ACTION,
  BROWSER_INSPECT_ELEMENT_ACTION,
  BROWSER_MANAGE_CSS_ACTION,
  BROWSER_MUTATE_DOM_ACTION,
  BROWSER_NAVIGATE_ACTION,
  BROWSER_GO_BACK_ACTION,
  BROWSER_GO_FORWARD_ACTION,
  BROWSER_ACTIVATE_TAB_ACTION,
  BROWSER_OPEN_TAB_ACTION,
  BROWSER_OBSERVE_EVENTS_ACTION,
  BROWSER_SCREENSHOT_ACTION,
  BROWSER_SET_CONTROL_IDENTITY_ACTION,
  BROWSER_SET_FILE_INPUT_FILES_ACTION,
  BROWSER_SELECT_OPTION_ACTION,
  BROWSER_SUBMIT_FORM_ACTION,
  BROWSER_GET_WORDPRESS_MENU_ACTION,
  BROWSER_EDIT_WORDPRESS_MENU_ACTION,
  BROWSER_GET_WORDPRESS_ADMIN_ACTION,
  BROWSER_WORDPRESS_LIST_TABLE_ACTION,
  BROWSER_GET_WORDPRESS_EDITOR_ACTION,
  BROWSER_EDIT_WORDPRESS_EDITOR_ACTION,
  BROWSER_TYPE_TEXT_ACTION,
  BROWSER_UNCHECK_ACTION,
  BROWSER_UNLOCK_TAB_ACTION,
  BROWSER_WAIT_FOR_ACTION,
  BROWSER_CONSOLE_ACTION,
  BROWSER_NETWORK_ACTION,
  BROWSER_EMULATE_DEVICE_ACTION,
  BROWSER_PERFORM_GESTURE_ACTION,
  BROWSER_PRINT_TO_PDF_ACTION,
  BROWSER_PAGE_API_REQUEST_ACTION,
  SYSTEM_CAPABILITIES_ACTION,
  SYSTEM_PING_ACTION,
} from "./factories.js";
import { parameterValidationError } from "./errors.js";
import {
  AuthenticateHttpParametersSchema,
  CaptureScreenshotParametersSchema,
  ClickAtParametersSchema,
  CloseTabParametersSchema,
  ClickElementParametersSchema,
  EvaluateJavaScriptParametersSchema,
  ExecuteJavaScriptParametersSchema,
  FindElementsParametersSchema,
  FindNaturalLanguageParametersSchema,
  GetPageSnapshotParametersSchema,
  GetPageTextParametersSchema,
  HandleJavaScriptDialogParametersSchema,
  HttpAuthStateParametersSchema,
  ListTabsParametersSchema,
  InspectElementParametersSchema,
  ManageCssParametersSchema,
  MutateDomParametersSchema,
  NavigateParametersSchema,
  HistoryNavigationParametersSchema,
  ActivateTabParametersSchema,
  OpenTabParametersSchema,
  ObserveEventsParametersSchema,
  SelectOptionParametersSchema,
  SetCheckedParametersSchema,
  SetControlIdentityParametersSchema,
  SetFileInputFilesParametersSchema,
  SubmitFormParametersSchema,
  GetWordPressMenuParametersSchema,
  EditWordPressMenuParametersSchema,
  GetWordPressAdminParametersSchema,
  WordPressListTableActionParametersSchema,
  GetWordPressEditorParametersSchema,
  EditWordPressEditorParametersSchema,
  SystemCapabilitiesParametersSchema,
  SystemPingParametersSchema,
  TypeTextParametersSchema,
  UnlockTabParametersSchema,
  WaitForParametersSchema,
  BrowserConsoleParametersSchema,
  NetworkCaptureParametersSchema,
  DeviceEmulationParametersSchema,
  PerformGestureParametersSchema,
  PrintToPdfParametersSchema,
  PageApiRequestParametersSchema,
} from "./schemas.js";

interface ActionParameterDefinition {
  schema: ZodType;
  keys: readonly string[];
}

const revisionKeys = ["tabId", "documentId", "domRevision", "elementId"] as const;

const definitions: Readonly<Record<string, ActionParameterDefinition>> = {
  [SYSTEM_PING_ACTION]: { schema: SystemPingParametersSchema, keys: ["sentAt", "nonce"] },
  [SYSTEM_CAPABILITIES_ACTION]: { schema: SystemCapabilitiesParametersSchema, keys: [] },
  [BROWSER_LIST_TABS_ACTION]: { schema: ListTabsParametersSchema, keys: [] },
  [BROWSER_OPEN_TAB_ACTION]: {
    schema: OpenTabParametersSchema,
    keys: ["url", "active", "waitUntil", "timeoutMs"],
  },
  [BROWSER_CLOSE_TAB_ACTION]: {
    schema: CloseTabParametersSchema,
    keys: ["tabId", "authorization"],
  },
  [BROWSER_NAVIGATE_ACTION]: {
    schema: NavigateParametersSchema,
    keys: ["tabId", "url", "active", "waitUntil", "timeoutMs"],
  },
  [BROWSER_GO_BACK_ACTION]: {
    schema: HistoryNavigationParametersSchema,
    keys: ["tabId", "waitUntil", "timeoutMs"],
  },
  [BROWSER_GO_FORWARD_ACTION]: {
    schema: HistoryNavigationParametersSchema,
    keys: ["tabId", "waitUntil", "timeoutMs"],
  },
  [BROWSER_ACTIVATE_TAB_ACTION]: {
    schema: ActivateTabParametersSchema,
    keys: ["tabId"],
  },
  [BROWSER_WAIT_FOR_ACTION]: {
    schema: WaitForParametersSchema,
    keys: ["tabId", "condition", "timeoutMs", "pollIntervalMs"],
  },
  [BROWSER_SET_CONTROL_IDENTITY_ACTION]: {
    schema: SetControlIdentityParametersSchema,
    keys: ["tabId", "agentName"],
  },
  [BROWSER_UNLOCK_TAB_ACTION]: { schema: UnlockTabParametersSchema, keys: ["tabId"] },
  [BROWSER_GET_PAGE_SNAPSHOT_ACTION]: {
    schema: GetPageSnapshotParametersSchema,
    keys: ["tabId", "detail", "includeHidden", "maxElements", "maxDepth", "maxTextLength", "scope"],
  },
  [BROWSER_GET_PAGE_TEXT_ACTION]: {
    schema: GetPageTextParametersSchema,
    keys: ["tabId", "maxChars", "format", "scope"],
  },
  [BROWSER_FIND_ELEMENTS_ACTION]: {
    schema: FindElementsParametersSchema,
    keys: [
      "tabId",
      "documentId",
      "domRevision",
      "text",
      "regex",
      "role",
      "name",
      "label",
      "placeholder",
      "title",
      "alt",
      "css",
      "xpath",
      "testId",
      "tag",
      "inputType",
      "visible",
      "enabled",
      "frameId",
      "proximity",
      "table",
      "parent",
      "matchMode",
      "caseSensitive",
      "maxResults",
    ],
  },
  [BROWSER_FIND_NATURAL_LANGUAGE_ACTION]: {
    schema: FindNaturalLanguageParametersSchema,
    keys: ["tabId", "query", "maxResults", "includeHidden"],
  },
  [BROWSER_CLICK_ACTION]: {
    schema: ClickElementParametersSchema,
    keys: [...revisionKeys, "scrollIntoView"],
  },
  [BROWSER_TYPE_TEXT_ACTION]: {
    schema: TypeTextParametersSchema,
    keys: [...revisionKeys, "text", "mode", "dispatchChange"],
  },
  [BROWSER_SET_FILE_INPUT_FILES_ACTION]: {
    schema: SetFileInputFilesParametersSchema,
    keys: [...revisionKeys, "filePaths", "authorization"],
  },
  [BROWSER_SELECT_OPTION_ACTION]: {
    schema: SelectOptionParametersSchema,
    keys: [...revisionKeys, "selection", "dispatchChange"],
  },
  [BROWSER_CHECK_ACTION]: { schema: SetCheckedParametersSchema, keys: revisionKeys },
  [BROWSER_UNCHECK_ACTION]: { schema: SetCheckedParametersSchema, keys: revisionKeys },
  [BROWSER_SUBMIT_FORM_ACTION]: {
    schema: SubmitFormParametersSchema,
    keys: [...revisionKeys, "authorization"],
  },
  [BROWSER_GET_WORDPRESS_MENU_ACTION]: {
    schema: GetWordPressMenuParametersSchema,
    keys: ["tabId", "maxItems"],
  },
  [BROWSER_EDIT_WORDPRESS_MENU_ACTION]: {
    schema: EditWordPressMenuParametersSchema,
    keys: ["tabId", "documentId", "domRevision", "operations", "save", "authorization"],
  },
  [BROWSER_GET_WORDPRESS_ADMIN_ACTION]: {
    schema: GetWordPressAdminParametersSchema,
    keys: ["tabId", "maxRows", "maxCellText"],
  },
  [BROWSER_WORDPRESS_LIST_TABLE_ACTION]: {
    schema: WordPressListTableActionParametersSchema,
    keys: [
      "tabId",
      "documentId",
      "domRevision",
      "operation",
      "rowId",
      "rowIds",
      "actionKey",
      "authorization",
    ],
  },
  [BROWSER_GET_WORDPRESS_EDITOR_ACTION]: {
    schema: GetWordPressEditorParametersSchema,
    keys: ["tabId", "maxContentChars"],
  },
  [BROWSER_EDIT_WORDPRESS_EDITOR_ACTION]: {
    schema: EditWordPressEditorParametersSchema,
    keys: ["tabId", "documentId", "domRevision", "fields", "save", "authorization"],
  },
  [BROWSER_EVALUATE_ACTION]: {
    schema: EvaluateJavaScriptParametersSchema,
    keys: ["tabId", "expression", "mode", "world", "authorization"],
  },
  [BROWSER_MUTATE_DOM_ACTION]: {
    schema: MutateDomParametersSchema,
    keys: [...revisionKeys, "operations", "authorization"],
  },
  [BROWSER_INSPECT_ELEMENT_ACTION]: {
    schema: InspectElementParametersSchema,
    keys: [
      ...revisionKeys,
      "computedStyleProperties",
      "includeEventListeners",
      "includeDocumentListeners",
      "listenerDepth",
      "maxListeners",
      "sourceExcerptChars",
    ],
  },
  [BROWSER_MANAGE_CSS_ACTION]: {
    schema: ManageCssParametersSchema,
    keys: ["operation", "tabId", "css", "origin", "allFrames", "injectionId", "authorization"],
  },
  [BROWSER_OBSERVE_EVENTS_ACTION]: {
    schema: ObserveEventsParametersSchema,
    keys: ["operation", "tabId", "eventTypes", "scope", "maxEvents", "captureId", "clear"],
  },
  [BROWSER_EXECUTE_JAVASCRIPT_ACTION]: {
    schema: ExecuteJavaScriptParametersSchema,
    keys: [
      "tabId",
      "source",
      "sourceType",
      "awaitPromise",
      "userGesture",
      "timeoutMs",
      "authorization",
    ],
  },
  [BROWSER_SCREENSHOT_ACTION]: {
    schema: CaptureScreenshotParametersSchema,
    keys: [
      "tabId",
      "quality",
      "maxWidth",
      "maxHeight",
      "mode",
      "documentId",
      "domRevision",
      "elementId",
      "padding",
      "region",
      "annotations",
    ],
  },
  [BROWSER_CLICK_AT_ACTION]: {
    schema: ClickAtParametersSchema,
    keys: ["tabId", "documentId", "domRevision", "x", "y"],
  },
  [BROWSER_GET_HTTP_AUTH_STATE_ACTION]: {
    schema: HttpAuthStateParametersSchema,
    keys: ["tabId"],
  },
  [BROWSER_AUTHENTICATE_HTTP_ACTION]: {
    schema: AuthenticateHttpParametersSchema,
    keys: ["tabId", "username", "password", "authorization", "timeoutMs"],
  },
  [BROWSER_HANDLE_JAVASCRIPT_DIALOG_ACTION]: {
    schema: HandleJavaScriptDialogParametersSchema,
    keys: ["tabId", "accept", "promptText", "trigger", "authorization", "timeoutMs"],
  },
  [BROWSER_CONSOLE_ACTION]: {
    schema: BrowserConsoleParametersSchema,
    keys: ["operation", "tabId", "bufferSize", "limit", "clear"],
  },
  [BROWSER_NETWORK_ACTION]: {
    schema: NetworkCaptureParametersSchema,
    keys: ["operation", "tabId", "bufferSize", "limit", "clear"],
  },
  [BROWSER_EMULATE_DEVICE_ACTION]: {
    schema: DeviceEmulationParametersSchema,
    keys: [
      "operation",
      "tabId",
      "preset",
      "orientation",
      "width",
      "height",
      "deviceScaleFactor",
      "touch",
    ],
  },
  [BROWSER_PERFORM_GESTURE_ACTION]: {
    schema: PerformGestureParametersSchema,
    keys: [
      "operation",
      "tabId",
      "documentId",
      "domRevision",
      "elementId",
      "targetElementId",
      "key",
      "code",
      "ctrl",
      "alt",
      "meta",
      "shift",
      "steps",
      "deltaX",
      "deltaY",
      "x",
      "y",
    ],
  },
  [BROWSER_PRINT_TO_PDF_ACTION]: {
    schema: PrintToPdfParametersSchema,
    keys: [
      "tabId",
      "landscape",
      "printBackground",
      "scale",
      "paperSize",
      "marginTop",
      "marginBottom",
      "marginLeft",
      "marginRight",
      "pageRanges",
      "preferCssPageSize",
    ],
  },
  [BROWSER_PAGE_API_REQUEST_ACTION]: {
    schema: PageApiRequestParametersSchema,
    keys: [
      "tabId",
      "url",
      "method",
      "headers",
      "body",
      "responseMode",
      "maxResponseChars",
      "useWordPressNonce",
      "authorization",
    ],
  },
};

export const parseActionParameters = (action: string, input: unknown): unknown => {
  const definition = definitions[action];
  if (definition === undefined) return input;
  const result = definition.schema.safeParse(input);
  if (!result.success) throw parameterValidationError(action, result.error, definition.keys);
  return result.data;
};

export const actionParameterKeys = (action: string): readonly string[] =>
  definitions[action]?.keys ?? [];
