import {
  SystemCapabilitiesDataSchema,
  actionParameterKeys,
  getActionMetadata,
  type BrowserCapability,
  type SystemCapabilitiesData,
} from "@invictum/protocol";

const actions: readonly BrowserCapability[] = [
  {
    action: "system.ping",
    riskLevel: "diagnostic",
    targeted: false,
    description: "Full extension round-trip health check",
  },
  {
    action: "system.capabilities",
    riskLevel: "diagnostic",
    targeted: false,
    description: "Runtime-supported actions and feature flags",
  },
  {
    action: "browser.list_tabs",
    riskLevel: "R0",
    targeted: false,
    description: "List redacted Chrome tab metadata",
  },
  {
    action: "browser.open_tab",
    riskLevel: "R1",
    targeted: false,
    description: "Open a validated HTTP(S) URL",
  },
  {
    action: "browser.close_tab",
    riskLevel: "R2",
    targeted: true,
    description: "Explicitly authorized tab close after proactive native-dialog handling",
  },
  {
    action: "browser.navigate",
    riskLevel: "R1",
    targeted: true,
    description: "Navigate a reserved tab to a validated HTTP(S) URL",
  },
  {
    action: "browser.go_back",
    riskLevel: "R1",
    targeted: true,
    description: "Navigate a reserved tab backward in its browser history",
  },
  {
    action: "browser.go_forward",
    riskLevel: "R1",
    targeted: true,
    description: "Navigate a reserved tab forward in its browser history",
  },
  {
    action: "browser.activate_tab",
    riskLevel: "R1",
    targeted: true,
    description: "Explicitly activate an existing tab only when foreground focus is required",
  },
  {
    action: "browser.wait_for",
    riskLevel: "R0",
    targeted: true,
    description: "Wait for URL, title, selector, text, or DOM stability",
  },
  {
    action: "browser.set_control_identity",
    riskLevel: "R0",
    targeted: true,
    description: "Show a safe per-tab agent name in the control indicator",
  },
  {
    action: "browser.get_page_snapshot",
    riskLevel: "R0",
    targeted: true,
    description: "Read a bounded semantic or subtree snapshot",
  },
  {
    action: "browser.get_page_text",
    riskLevel: "R0",
    targeted: true,
    description: "Read bounded clean page or subtree text from sanitized semantic blocks",
  },
  {
    action: "browser.find_elements",
    riskLevel: "R0",
    targeted: true,
    description: "Find revision-bound semantic elements",
  },
  {
    action: "browser.find_natural_language",
    riskLevel: "R0",
    targeted: true,
    description: "Find ranked semantic controls using a deterministic natural-language query",
  },
  {
    action: "browser.click",
    riskLevel: "R1",
    targeted: true,
    description: "Click a revision-bound semantic element",
  },
  {
    action: "browser.type_text",
    riskLevel: "R1",
    targeted: true,
    description: "Type into a nonsensitive field or editor",
  },
  {
    action: "browser.set_file_input_files",
    riskLevel: "R2",
    targeted: true,
    description: "Attach explicitly authorized local files to a file input",
  },
  {
    action: "browser.select_option",
    riskLevel: "R1",
    targeted: true,
    description: "Select native options",
  },
  {
    action: "browser.check",
    riskLevel: "R1",
    targeted: true,
    description: "Check a native checkbox or radio",
  },
  {
    action: "browser.uncheck",
    riskLevel: "R1",
    targeted: true,
    description: "Uncheck a native checkbox",
  },
  {
    action: "browser.submit_form",
    riskLevel: "R2",
    targeted: true,
    description: "Explicitly authorized form submission",
  },
  {
    action: "browser.get_figma_document",
    riskLevel: "R0",
    targeted: true,
    description: "Read the page list, mode, and selection of an open Figma design file",
  },
  {
    action: "browser.get_figma_layers",
    riskLevel: "R0",
    targeted: true,
    description: "Read the rendered rows of the Figma layer tree for the current page",
  },
  {
    action: "browser.get_figma_properties",
    riskLevel: "R0",
    targeted: true,
    description: "Read properties of the current Figma selection, preferring Dev Mode CSS",
  },
  {
    action: "browser.figma_select",
    riskLevel: "R1",
    targeted: true,
    description: "Switch the Figma page, mode, or selected layer through its own controls",
  },
  {
    action: "browser.figma_healthcheck",
    riskLevel: "R0",
    targeted: true,
    description: "Verify that every Figma UI anchor the adapter depends on still resolves",
  },
  {
    action: "browser.get_wordpress_menu",
    riskLevel: "R0",
    targeted: true,
    description: "Read the current classic WordPress navigation-menu tree",
  },
  {
    action: "browser.edit_wordpress_menu",
    riskLevel: "R2",
    targeted: true,
    description: "Add, update, remove, reorganize, or save WordPress menu items",
  },
  {
    action: "browser.get_wordpress_admin",
    riskLevel: "R0",
    targeted: true,
    description: "Read bounded WordPress admin context, notices, and list-table rows/actions",
  },
  {
    action: "browser.wordpress_list_table_action",
    riskLevel: "R2",
    targeted: true,
    description: "Open a typed row action or apply an explicitly authorized bulk action",
  },
  {
    action: "browser.get_wordpress_editor",
    riskLevel: "R0",
    targeted: true,
    description: "Read the authoritative Gutenberg or Classic post-editor model",
  },
  {
    action: "browser.edit_wordpress_editor",
    riskLevel: "R2",
    targeted: true,
    description: "Edit typed Gutenberg or Classic post fields and optionally save",
  },
  {
    action: "browser.evaluate",
    riskLevel: "R2",
    targeted: true,
    description: "Policy-constrained DOM JavaScript",
  },
  {
    action: "browser.mutate_dom",
    riskLevel: "R2",
    targeted: true,
    description: "Typed DOM, attribute, sanitized HTML, and inline-style mutation",
  },
  {
    action: "browser.inspect_element",
    riskLevel: "R0",
    targeted: true,
    description: "Inspect element state, computed CSS, listeners, and bounded source excerpts",
  },
  {
    action: "browser.manage_css",
    riskLevel: "R2",
    targeted: true,
    description: "Inject or remove bounded CSS with automatic unlock cleanup",
  },
  {
    action: "browser.observe_events",
    riskLevel: "R0",
    targeted: true,
    description: "Start, read, or stop bounded value-redacted DOM event capture",
  },
  {
    action: "browser.execute_javascript",
    riskLevel: "R3",
    targeted: true,
    description: "Explicitly authorized raw JavaScript through a short-lived debugger session",
  },
  {
    action: "browser.console",
    riskLevel: "R0",
    targeted: true,
    description: "Start, read, clear, or stop bounded and redacted browser-console capture",
  },
  {
    action: "browser.network",
    riskLevel: "R0",
    targeted: true,
    description: "Start, read, clear, or stop bounded metadata-only network capture",
  },
  {
    action: "browser.emulate_device",
    riskLevel: "R1",
    targeted: true,
    description: "Set, inspect, or reset reversible mobile viewport and touch emulation",
  },
  {
    action: "browser.screenshot",
    riskLevel: "R0",
    targeted: true,
    description: "Bounded viewport, element, region, or full-page JPEG with safe annotations",
  },
  {
    action: "browser.click_at",
    riskLevel: "R1",
    targeted: true,
    description: "Revision-bound coordinate fallback click",
  },
  {
    action: "browser.perform_gesture",
    riskLevel: "R1",
    targeted: true,
    description: "Revision-bound hover, focus, keyboard, scroll, or drag-and-drop gesture",
  },
  {
    action: "browser.get_terminals",
    riskLevel: "R0",
    targeted: true,
    description: "Detect xterm-compatible terminal widgets without reading terminal output",
  },
  {
    action: "browser.read_terminal",
    riskLevel: "R2",
    targeted: true,
    description: "Explicitly authorized bounded and redacted xterm buffer readback",
  },
  {
    action: "browser.terminal_input",
    riskLevel: "R3",
    targeted: true,
    description: "Explicitly authorized trusted terminal text, command, or special-key input",
  },
  {
    action: "browser.print_to_pdf",
    riskLevel: "R0",
    targeted: true,
    description: "Export the current HTTP(S) page as a bounded PDF document",
  },
  {
    action: "browser.page_api_request",
    riskLevel: "R3",
    targeted: true,
    description: "Explicitly authorized same-origin page API request with credential redaction",
  },
  {
    action: "browser.unlock_tab",
    riskLevel: "R0",
    targeted: true,
    description: "Release the agent reservation",
  },
  {
    action: "browser.get_http_auth_state",
    riskLevel: "R0",
    targeted: true,
    description: "Read a recent sanitized HTTP authentication challenge",
  },
  {
    action: "browser.authenticate_http",
    riskLevel: "R2",
    targeted: true,
    description: "Explicitly authorized, ephemeral HTTP Basic authentication",
  },
  {
    action: "browser.handle_javascript_dialog",
    riskLevel: "R2",
    targeted: true,
    description: "Explicitly authorized accept or dismissal of a native JavaScript dialog",
  },
];

export const getExtensionCapabilities = (): SystemCapabilitiesData =>
  SystemCapabilitiesDataSchema.parse({
    protocol: "ibp",
    protocolVersion: "1.0",
    component: "extension",
    extensionVersion: chrome.runtime.getManifest().version,
    actions: actions.map((capability) => {
      const metadata = getActionMetadata(capability.action);
      if (metadata === undefined || metadata.riskLevel !== capability.riskLevel) {
        throw new Error(`Missing or inconsistent action metadata for ${capability.action}`);
      }
      return {
        ...capability,
        readOnly: metadata.readOnly,
        destructive: metadata.destructive,
        idempotent: metadata.idempotent,
        requiresAuthorization: metadata.requiresAuthorization,
        parameterKeys: [...actionParameterKeys(capability.action)],
      };
    }),
    features: {
      figmaDesignFiles: true,
      agentWindow: true,
      persistentHttpHostAccess: true,
      semanticSnapshots: true,
      scopedSnapshots: true,
      compactSnapshots: true,
      outlineSnapshots: true,
      previousRevisionRelocation: true,
      structuredParameterErrors: true,
      screenshots: true,
      screenshotModes: true,
      screenshotAnnotations: true,
      coordinateFallback: true,
      prefilledCredentialPresence: true,
      httpBasicAuth: true,
      nativeJavaScriptDialogs: true,
      localFileUpload: true,
      wordpressMenuEditing: true,
      wordpressAdminTools: true,
      wordpressPostEditing: true,
      elementInspection: true,
      domMutation: true,
      cssInjection: true,
      eventCapture: true,
      browserConsole: true,
      networkCapture: true,
      deviceEmulation: true,
      advancedGestures: true,
      pageText: true,
      naturalLanguageFind: true,
      historyNavigation: true,
      explicitTabActivation: true,
      sameOriginPageApi: true,
      agentBatching: true,
      pdfExport: true,
      rawJavaScript: true,
      customControlIdentity: true,
      configurableTabActivation: true,
      terminalAutomation: true,
      trustedTerminalInput: true,
      terminalBufferReadback: true,
      terminalTransportReadback: true,
      userStop: true,
    },
  });
